name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH Key
        run: |
          $env:SSH_KEY_CONTENT = "${{ secrets.SERVER_SSH_KEY }}"
          $env:SSH_KEY_PATH = "C:\\Users\\DELL\\.ssh\\id_rsa.pub"
          
          # Tạo thư mục .ssh nếu chưa tồn tại
          $sshDir = "$env:USERPROFILE\.ssh"
          if (-Not (Test-Path $sshDir)) {
              Write-Output "Creating .ssh directory"
              New-Item -Path $sshDir -ItemType Directory -Force
          }

          # Xóa tệp SSH key cũ nếu tồn tại
          $keyPath = "$env:USERPROFILE\.ssh\id_rsa.pub"
          if (Test-Path $keyPath) {
              Write-Output "Removing existing SSH key"
              Remove-Item -Path $keyPath -Force
          }

          # Lưu SSH key vào tệp
          Write-Output "Writing SSH key to $keyPath"
          [System.IO.File]::WriteAllText($keyPath, $env:SSH_KEY_CONTENT)
          
          # Đặt quyền truy cập cho tệp SSH key
          Write-Output "Setting permissions for $keyPath"
          icacls $keyPath /inheritance:r
          icacls $keyPath /grant:r "${env:USERNAME}:(R)"
        shell: C:\Program Files\PowerShell\7\pwsh.EXE -command ". '{0}'"

      - name: Sync WordPress Files to Server
        run: |
          $env:REMOTE_HOST = "${{ secrets.SERVER_HOST }}"
          $env:REMOTE_USER = "${{ secrets.SERVER_USER }}"
          $env:REMOTE_PATH = "/path/to/your/wordpress/directory/"
          $env:SCP_CMD = "scp -i C:\\Users\\DELL\\.ssh\\id_rsa.pub -r C:\\xampp\\htdocs\\foodorder\\* $env:REMOTE_USER@$env:REMOTE_HOST:$env:REMOTE_PATH"
          Write-Output "Running SCP command to sync WordPress files: $env:SCP_CMD"
          Invoke-Expression -Command $env:SCP_CMD

      - name: Sync Nginx Configuration to Server
        run: |
          $env:REMOTE_HOST = "${{ secrets.SERVER_HOST }}"
          $env:REMOTE_USER = "${{ secrets.SERVER_USER }}"
          $env:REMOTE_PATH = "/path/to/your/nginx/directory/nginx.conf"
          $env:SCP_CMD = "scp -i C:\\Users\\DELL\\.ssh\\id_rsa.pub C:\\nginx-1.25.5\\conf\\nginx.conf $env:REMOTE_USER@$env:REMOTE_HOST:$env:REMOTE_PATH"
          Write-Output "Running SCP command to sync Nginx config: $env:SCP_CMD"
          Invoke-Expression -Command $env:SCP_CMD

      - name: Restart Web Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            net stop nginx
            net start nginx
