name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync WordPress Files to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: C:/xampp/htdocs/foodorder/
        remote_path: /path/to/your/wordpress/directory/ # Thay đổi đường dẫn này với đường dẫn trên server của bạn
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Sync Nginx Configuration to Server
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: C:/nginx-1.25.5/conf/nginx.conf
        remote_path: /path/to/your/nginx/directory/nginx.conf # Thay đổi đường dẫn này với đường dẫn trên server của bạn
        remote_host: ${{ secrets.SERVER_HOST }}
        remote_user: ${{ secrets.SERVER_USER }}
        remote_key: ${{ secrets.SERVER_SSH_KEY }}

    - name: Restart Web Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          net stop nginx
          net start nginx
