name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Sync WordPress Files to Server
      run: |
        $env:REMOTE_HOST = "${{ secrets.SERVER_HOST }}"
        $env:REMOTE_USER = "${{ secrets.SERVER_USER }}"
        $env:REMOTE_PATH = "/path/to/your/wordpress/directory/"  # Thay đổi đường dẫn này với đường dẫn trên server của bạn
        $env:SSH_KEY = "${{ secrets.SERVER_SSH_KEY }}"

        scp -i $env:SSH_KEY -r C:/xampp/htdocs/foodorder/* $env:REMOTE_USER@$env:REMOTE_HOST:$env:REMOTE_PATH

    - name: Sync Nginx Configuration to Server
      run: |
        $env:REMOTE_HOST = "${{ secrets.SERVER_HOST }}"
        $env:REMOTE_USER = "${{ secrets.SERVER_USER }}"
        $env:REMOTE_PATH = "/path/to/your/nginx/directory/nginx.conf"  # Thay đổi đường dẫn này với đường dẫn trên server của bạn
        $env:SSH_KEY = "${{ secrets.SERVER_SSH_KEY }}"

        scp -i $env:SSH_KEY C:/nginx-1.25.5/conf/nginx.conf $env:REMOTE_USER@$env:REMOTE_HOST:$env:REMOTE_PATH

    - name: Restart Web Server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        script: |
          net stop nginx
          net start nginx
